import { Politician } from './types';

// Brevard County, Florida Officials (2026)
// County seat: Titusville (historical), Viera (government center)
// Population: ~620,000

export const brevardCountyOfficials: Politician[] = [
  // County Commissioners (5)
  {
    id: 'bc-001',
    name: 'Katie Delaney',
    office: 'County Commissioner District 1',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 1',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Commissioner representing District 1.',
    socialMedia: {},
  },
  {
    id: 'bc-002',
    name: 'Tom Goodson',
    office: 'County Commissioner District 2, Vice Chair',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 2',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Commissioner and Vice Chair representing District 2.',
    socialMedia: {},
  },
  {
    id: 'bc-003',
    name: 'Kim Adkinson',
    office: 'County Commissioner District 3',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 3',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Commissioner representing District 3.',
    socialMedia: {},
  },
  {
    id: 'bc-004',
    name: 'Rob Feltner',
    office: 'County Commissioner District 4, Chair',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 4',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Commission Chair representing District 4.',
    socialMedia: {},
  },
  {
    id: 'bc-005',
    name: 'Thad Altman',
    office: 'County Commissioner District 5',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 5',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Commissioner representing District 5; former State Senator and State Representative.',
    socialMedia: {},
  },

  // Constitutional Officers (5)
  {
    id: 'bc-006',
    name: 'Wayne Ivey',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Sheriff; known for community engagement through social media.',
    socialMedia: {},
  },
  {
    id: 'bc-007',
    name: 'Rachel Sadoff',
    office: 'Clerk of Circuit Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Clerk of Circuit Court and Comptroller.',
    socialMedia: {},
  },
  {
    id: 'bc-008',
    name: 'Dana Blickley',
    office: 'Property Appraiser',
    officeLevel: 'Property Appraiser',
    party: 'Republican',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Property Appraiser; responsible for property valuations countywide.',
    socialMedia: {},
  },
  {
    id: 'bc-009',
    name: 'Lisa Cullen',
    office: 'Tax Collector',
    officeLevel: 'Tax Collector',
    party: 'Republican',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Tax Collector; manages tax collection and motor vehicle services.',
    socialMedia: {},
  },
  {
    id: 'bc-010',
    name: 'Tim Bobanic',
    office: 'Supervisor of Elections',
    officeLevel: 'Supervisor of Elections',
    party: 'Republican',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County Supervisor of Elections; oversees voter registration and election administration.',
    socialMedia: {},
  },

  // School Board (5)
  {
    id: 'bc-011',
    name: 'Megan Wright',
    office: 'School Board District 1',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 1',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County School Board member representing District 1.',
    socialMedia: {},
  },
  {
    id: 'bc-012',
    name: 'Gene Trent',
    office: 'School Board District 2, Chair',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 2',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County School Board Chair representing District 2.',
    socialMedia: {},
  },
  {
    id: 'bc-013',
    name: 'John Thomas',
    office: 'School Board District 3',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 3',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County School Board member representing District 3.',
    socialMedia: {},
  },
  {
    id: 'bc-014',
    name: 'Matt Susin',
    office: 'School Board District 4, Vice Chair',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 4',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County School Board Vice Chair representing District 4.',
    socialMedia: {},
  },
  {
    id: 'bc-015',
    name: 'Katye Campbell',
    office: 'School Board District 5',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 5',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Brevard County School Board member representing District 5.',
    socialMedia: {},
  },

  // Mayors (9)
  {
    id: 'bc-016',
    name: 'Paul Alfrey',
    office: 'Mayor of Melbourne',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Melbourne; leads the largest city in Brevard County.',
    socialMedia: {},
  },
  {
    id: 'bc-017',
    name: 'Rob Medina',
    office: 'Mayor of Palm Bay',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Palm Bay; leads the most populous city in Brevard County.',
    socialMedia: {},
  },
  {
    id: 'bc-018',
    name: 'Andrew Connors',
    office: 'Mayor of Titusville',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Titusville; serves the historic Space Coast gateway city near Kennedy Space Center.',
    socialMedia: {},
  },
  {
    id: 'bc-019',
    name: 'Mike Blake',
    office: 'Mayor of Cocoa',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Cocoa; leads the historic central Brevard County city.',
    socialMedia: {},
  },
  {
    id: 'bc-020',
    name: 'Tom Price',
    office: 'Mayor of Rockledge',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Rockledge; serves the oldest incorporated city in Brevard County.',
    socialMedia: {},
  },
  {
    id: 'bc-021',
    name: 'Keith Capizzi',
    office: 'Mayor of Cocoa Beach',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Cocoa Beach; leads the popular beachside community on the Space Coast.',
    socialMedia: {},
  },
  {
    id: 'bc-022',
    name: 'Steven Osmer',
    office: 'Mayor of Satellite Beach',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Satellite Beach; serves the barrier island community in south Brevard.',
    socialMedia: {},
  },
  {
    id: 'bc-023',
    name: 'Scott Nickle',
    office: 'Mayor of Indian Harbour Beach',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Indian Harbour Beach; leads the beachside community between Melbourne and Patrick Space Force Base.',
    socialMedia: {},
  },
  {
    id: 'bc-024',
    name: 'Wes Morrison',
    office: 'Mayor of Cape Canaveral',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Brevard County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Cape Canaveral; leads the city adjacent to the Cape Canaveral Space Force Station.',
    socialMedia: {},
  },
];
