import { Politician } from './types';

export const flaglerCountyOfficials: Politician[] = [
  // ── COUNTY COMMISSIONERS ──────────────────────────────────────────────
  {
    id: 'fc-001',
    name: 'Andy Dance',
    office: 'County Commissioner, District 1',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 1',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler County Commissioner representing District 1.',
    socialMedia: {},
  },
  {
    id: 'fc-002',
    name: 'Greg Hansen',
    office: 'County Commissioner, District 2',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 2',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler County Commissioner representing District 2.',
    socialMedia: {},
  },
  {
    id: 'fc-003',
    name: 'Kim Carney',
    office: 'County Commissioner, District 3 (Vice Chair)',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 3',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler County Commissioner representing District 3, serving as Vice Chair.',
    socialMedia: {},
  },
  {
    id: 'fc-004',
    name: 'Leann Pennington',
    office: 'County Commissioner, District 4 (Chair)',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 4',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler County Commissioner representing District 4, serving as Chair.',
    socialMedia: {},
  },
  {
    id: 'fc-005',
    name: 'Pam Richardson',
    office: 'County Commissioner, District 5',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 5',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler County Commissioner representing District 5.',
    socialMedia: {},
  },

  // ── CONSTITUTIONAL OFFICERS ───────────────────────────────────────────
  {
    id: 'fc-006',
    name: 'Rick Staly',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Sheriff of Flagler County.',
    socialMedia: {},
  },
  {
    id: 'fc-007',
    name: 'Tom Bexley',
    office: 'Clerk of Circuit Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Clerk of Circuit Court for Flagler County.',
    socialMedia: {},
  },
  {
    id: 'fc-008',
    name: 'Jay Gardner',
    office: 'Property Appraiser',
    officeLevel: 'Property Appraiser',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Property Appraiser for Flagler County.',
    socialMedia: {},
  },
  {
    id: 'fc-009',
    name: 'Shelly Edmonson',
    office: 'Tax Collector',
    officeLevel: 'Tax Collector',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Tax Collector for Flagler County.',
    socialMedia: {},
  },
  {
    id: 'fc-010',
    name: 'Kaiti Lenhart',
    office: 'Supervisor of Elections',
    officeLevel: 'Supervisor of Elections',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Supervisor of Elections for Flagler County.',
    socialMedia: {},
  },

  // ── SCHOOL BOARD ──────────────────────────────────────────────────────
  {
    id: 'fc-011',
    name: 'Will Furry',
    office: 'School Board Member, District 2 (Vice Chair)',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 2',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler County School Board member representing District 2, serving as Vice Chair.',
    socialMedia: {},
  },
  {
    id: 'fc-012',
    name: 'Janie Ruddy',
    office: 'School Board Member, District 3',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 3',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler County School Board member representing District 3.',
    socialMedia: {},
  },
  {
    id: 'fc-013',
    name: 'Christy Chong',
    office: 'School Board Member, District 4 (Chair)',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 4',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler County School Board member representing District 4, serving as Chair.',
    socialMedia: {},
  },
  {
    id: 'fc-014',
    name: 'Lauren Ramirez',
    office: 'School Board Member, District 5',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 5',
    jurisdiction: 'Flagler County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler County School Board member representing District 5.',
    socialMedia: {},
  },

  // ── PALM COAST ────────────────────────────────────────────────────────
  {
    id: 'fc-015',
    name: 'Mike Norris',
    office: 'Mayor of Palm Coast',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    district: 'Citywide',
    jurisdiction: 'Palm Coast',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Mayor of Palm Coast.',
    socialMedia: {},
  },
  {
    id: 'fc-016',
    name: 'Ty Miller',
    office: 'Council Member, District 1',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'District 1',
    jurisdiction: 'Palm Coast',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Palm Coast City Council member representing District 1.',
    socialMedia: {},
  },
  {
    id: 'fc-017',
    name: 'Theresa Carli Pontieri',
    office: 'Vice Mayor, District 2',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'District 2',
    jurisdiction: 'Palm Coast',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Vice Mayor of Palm Coast representing District 2.',
    socialMedia: {},
  },
  {
    id: 'fc-018',
    name: 'David Sullivan',
    office: 'Council Member, District 3',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'District 3',
    jurisdiction: 'Palm Coast',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Palm Coast City Council member representing District 3.',
    socialMedia: {},
  },
  {
    id: 'fc-019',
    name: 'Charles A. Gambaro Jr.',
    office: 'Council Member, District 4',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'District 4',
    jurisdiction: 'Palm Coast',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Palm Coast City Council member representing District 4.',
    socialMedia: {},
  },

  // ── FLAGLER BEACH ─────────────────────────────────────────────────────
  {
    id: 'fc-020',
    name: 'Patti King',
    office: 'Mayor of Flagler Beach',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    district: 'Citywide',
    jurisdiction: 'Flagler Beach',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Mayor of Flagler Beach.',
    socialMedia: {},
  },
  {
    id: 'fc-021',
    name: 'James Sherman',
    office: 'Commissioner (Chair)',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Flagler Beach',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler Beach City Commissioner serving as Chair.',
    socialMedia: {},
  },
  {
    id: 'fc-022',
    name: 'Eric Cooley',
    office: 'Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Flagler Beach',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler Beach City Commissioner.',
    socialMedia: {},
  },
  {
    id: 'fc-023',
    name: 'John Cunningham',
    office: 'Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Flagler Beach',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler Beach City Commissioner.',
    socialMedia: {},
  },
  {
    id: 'fc-024',
    name: 'Scott Spradley',
    office: 'Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Flagler Beach',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler Beach City Commissioner.',
    socialMedia: {},
  },
  {
    id: 'fc-025',
    name: 'R.J. Santore',
    office: 'Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Flagler Beach',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Flagler Beach City Commissioner.',
    socialMedia: {},
  },

  // ── BUNNELL ───────────────────────────────────────────────────────────
  {
    id: 'fc-026',
    name: 'Catherine Robinson',
    office: 'Mayor of Bunnell',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    district: 'Citywide',
    jurisdiction: 'Bunnell',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Mayor of Bunnell.',
    socialMedia: {},
  },
  {
    id: 'fc-027',
    name: 'John Rogers',
    office: 'Vice Mayor/Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Bunnell',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Vice Mayor and Commissioner of Bunnell.',
    socialMedia: {},
  },
  {
    id: 'fc-028',
    name: 'Pete Young',
    office: 'Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Bunnell',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Bunnell City Commissioner.',
    socialMedia: {},
  },
  {
    id: 'fc-029',
    name: 'David Atkinson',
    office: 'Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Bunnell',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Bunnell City Commissioner.',
    socialMedia: {},
  },
  {
    id: 'fc-030',
    name: 'Dean Sechrist',
    office: 'Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Bunnell',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Bunnell City Commissioner.',
    socialMedia: {},
  },
];
