import { Politician } from './types';

export const lakeCountyOfficials: Politician[] = [
  // ─── COUNTY COMMISSIONERS ───────────────────────────────────────────
  {
    id: 'lc-001',
    name: 'Anthony Sabatini',
    office: 'County Commissioner',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 1',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County Commissioner for District 1, attorney and former state legislator known for conservative policy positions.',
    socialMedia: {},
  },
  {
    id: 'lc-002',
    name: 'Sean Parks',
    office: 'County Commissioner',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 2',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County Commissioner for District 2, focused on infrastructure development and fiscal responsibility.',
    socialMedia: {},
  },
  {
    id: 'lc-003',
    name: 'Kirby Smith',
    office: 'County Commissioner',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 3',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County Commissioner for District 3, advocate for rural communities and sustainable county growth.',
    socialMedia: {},
  },
  {
    id: 'lc-004',
    name: 'Leslie Campione',
    office: 'County Commissioner, Chairman',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 4',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Chairman of the Lake County Board of County Commissioners representing District 4, long-serving local leader.',
    socialMedia: {},
  },
  {
    id: 'lc-005',
    name: 'Timothy Morris',
    office: 'County Commissioner',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 5',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County Commissioner for District 5, focused on public safety and economic development initiatives.',
    socialMedia: {},
  },

  // ─── CONSTITUTIONAL OFFICERS ────────────────────────────────────────
  {
    id: 'lc-006',
    name: 'Peyton Grinnell',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County Sheriff overseeing law enforcement operations across the county.',
    socialMedia: {},
  },
  {
    id: 'lc-007',
    name: 'Gary J. Cooney',
    office: 'Clerk of Circuit Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County Clerk of Circuit Court responsible for court records and county financial oversight.',
    socialMedia: {},
  },
  {
    id: 'lc-008',
    name: 'Mark Jordan',
    office: 'Property Appraiser',
    officeLevel: 'Property Appraiser',
    party: 'Republican',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County Property Appraiser responsible for determining the value of all real and tangible property in the county.',
    socialMedia: {},
  },
  {
    id: 'lc-009',
    name: 'David Jordan',
    office: 'Tax Collector',
    officeLevel: 'Tax Collector',
    party: 'Republican',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County Tax Collector managing tax collection, vehicle registration, and driver license services.',
    socialMedia: {},
  },
  {
    id: 'lc-010',
    name: 'Alan Hays',
    office: 'Supervisor of Elections',
    officeLevel: 'Supervisor of Elections',
    party: 'Republican',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County Supervisor of Elections overseeing voter registration and election administration.',
    socialMedia: {},
  },

  // ─── SCHOOL BOARD ───────────────────────────────────────────────────
  {
    id: 'lc-011',
    name: 'William John Mathias',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 1',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County School Board member for District 1, working on education policy and school funding.',
    socialMedia: {},
  },
  {
    id: 'lc-012',
    name: 'Tyler Brandeburg',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 2',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County School Board member for District 2, focused on student achievement and curriculum standards.',
    socialMedia: {},
  },
  {
    id: 'lc-013',
    name: 'Marc Dodd',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 3',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County School Board member for District 3, advocating for teacher support and school safety.',
    socialMedia: {},
  },
  {
    id: 'lc-014',
    name: 'Mollie Cunningham',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 4',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County School Board member for District 4, dedicated to improving educational outcomes and community engagement.',
    socialMedia: {},
  },
  {
    id: 'lc-015',
    name: 'Stephanie Luke',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 5',
    jurisdiction: 'Lake County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Lake County School Board member for District 5, committed to fiscal transparency and student wellbeing.',
    socialMedia: {},
  },

  // ─── MAYORS ─────────────────────────────────────────────────────────
  {
    id: 'lc-016',
    name: 'Lori Pfister',
    office: 'Mayor of Tavares',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Lake County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Tavares, the county seat of Lake County, leading municipal governance and community development.',
    socialMedia: {},
  },
  {
    id: 'lc-017',
    name: 'Allyson Berry',
    office: 'Mayor of Leesburg',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Lake County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Leesburg, overseeing one of Lake County\'s largest cities and its economic growth initiatives.',
    socialMedia: {},
  },
  {
    id: 'lc-018',
    name: 'Tim Murry',
    office: 'Mayor of Clermont',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Lake County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Clermont, managing rapid population growth and infrastructure expansion in south Lake County.',
    socialMedia: {},
  },
  {
    id: 'lc-019',
    name: 'Willie Hawkins',
    office: 'Mayor of Eustis',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Lake County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Eustis, focused on downtown revitalization and community services for residents.',
    socialMedia: {},
  },
  {
    id: 'lc-020',
    name: 'James Homich',
    office: 'Mayor of Mount Dora',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Lake County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Mount Dora, preserving the city\'s historic character while supporting small business growth.',
    socialMedia: {},
  },
  {
    id: 'lc-021',
    name: 'Ed Freeman',
    office: 'Mayor-Commissioner of Lady Lake',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Lake County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor-Commissioner of Lady Lake, serving a community at the gateway to The Villages retirement area.',
    socialMedia: {},
  },
  {
    id: 'lc-022',
    name: 'Pat Kelley',
    office: 'Mayor of Minneola',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Lake County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Minneola, guiding one of Lake County\'s fastest-growing municipalities through expansion.',
    socialMedia: {},
  },
  {
    id: 'lc-023',
    name: 'Keith Keogh',
    office: 'Mayor of Groveland',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Lake County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Groveland, overseeing significant residential development and city service expansion.',
    socialMedia: {},
  },
  {
    id: 'lc-024',
    name: 'Steven Sheffield',
    office: 'Mayor of Mascotte',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Lake County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Mascotte, working to improve city infrastructure and attract economic investment.',
    socialMedia: {},
  },
];
