import { Politician } from './types';

// Orange County, Florida Officials (2026)
// County seat: Orlando
// Population: ~1,450,000

export const orangeCountyOfficials: Politician[] = [
  // County Mayor + Commissioners (7)
  {
    id: 'oc-001',
    name: 'Jerry L. Demings',
    office: 'Orange County Mayor',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Mayor serving at-large; former Orange County Sheriff and Orlando Police Chief.',
    socialMedia: {},
  },
  {
    id: 'oc-002',
    name: 'Nicole H. Wilson',
    office: 'County Commissioner District 1',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'District 1',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Commissioner representing District 1.',
    socialMedia: {},
  },
  {
    id: 'oc-003',
    name: 'Christine Moore',
    office: 'County Commissioner District 2',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 2',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Commissioner representing District 2.',
    socialMedia: {},
  },
  {
    id: 'oc-004',
    name: 'Mayra Uribe',
    office: 'County Commissioner District 3',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'District 3',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Commissioner representing District 3.',
    socialMedia: {},
  },
  {
    id: 'oc-005',
    name: 'Maribel Gomez Cordero',
    office: 'County Commissioner District 4',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'District 4',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Commissioner representing District 4.',
    socialMedia: {},
  },
  {
    id: 'oc-006',
    name: 'Kelly Martinez Semrad',
    office: 'County Commissioner District 5',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'District 5',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Commissioner representing District 5.',
    socialMedia: {},
  },
  {
    id: 'oc-007',
    name: 'Michael "Mike" Scott',
    office: 'County Commissioner District 6',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'District 6',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Commissioner representing District 6.',
    socialMedia: {},
  },

  // Constitutional Officers (5)
  {
    id: 'oc-008',
    name: 'John Mina',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Democrat',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Sheriff; former Orlando Police Chief.',
    socialMedia: {},
  },
  {
    id: 'oc-009',
    name: 'Tiffany Moore Russell',
    office: 'Clerk of Circuit Court',
    officeLevel: 'Clerk of Court',
    party: 'Democrat',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Clerk of Circuit Court and Comptroller.',
    socialMedia: {},
  },
  {
    id: 'oc-010',
    name: 'Amy Mercado',
    office: 'Property Appraiser',
    officeLevel: 'Property Appraiser',
    party: 'Democrat',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Property Appraiser; former State Representative.',
    socialMedia: {},
  },
  {
    id: 'oc-011',
    name: 'Scott Randolph',
    office: 'Tax Collector',
    officeLevel: 'Tax Collector',
    party: 'Democrat',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Tax Collector; former State Representative.',
    socialMedia: {},
  },
  {
    id: 'oc-012',
    name: 'Karen Castor Dentel',
    office: 'Supervisor of Elections',
    officeLevel: 'Supervisor of Elections',
    party: 'Democrat',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County Supervisor of Elections; oversees voter registration and election administration.',
    socialMedia: {},
  },

  // School Board (7)
  {
    id: 'oc-013',
    name: 'Angie Gallo',
    office: 'School Board District 1',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 1',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County School Board member representing District 1.',
    socialMedia: {},
  },
  {
    id: 'oc-014',
    name: 'Maria Salamanca',
    office: 'School Board District 2',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 2',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County School Board member representing District 2.',
    socialMedia: {},
  },
  {
    id: 'oc-015',
    name: 'Alicia Farrant',
    office: 'School Board District 3',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 3',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County School Board member representing District 3.',
    socialMedia: {},
  },
  {
    id: 'oc-016',
    name: 'Anne Douglas',
    office: 'School Board District 4',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 4',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County School Board member representing District 4.',
    socialMedia: {},
  },
  {
    id: 'oc-017',
    name: 'Vicki-Elaine Felder',
    office: 'School Board District 5',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 5',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County School Board member representing District 5.',
    socialMedia: {},
  },
  {
    id: 'oc-018',
    name: 'Stephanie Vanos',
    office: 'School Board District 6',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 6',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County School Board member representing District 6.',
    socialMedia: {},
  },
  {
    id: 'oc-019',
    name: 'Melissa Byrd',
    office: 'School Board District 7 Vice Chair',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 7',
    jurisdiction: 'Orange County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Orange County School Board Vice Chair representing District 7.',
    socialMedia: {},
  },

  // Mayors (9)
  {
    id: 'oc-020',
    name: 'Buddy Dyer',
    office: 'Mayor of Orlando',
    officeLevel: 'Mayor',
    party: 'Democrat',
    jurisdiction: 'Orange County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Orlando; longest-serving mayor in the city\'s history.',
    socialMedia: {},
  },
  {
    id: 'oc-021',
    name: 'Sheila DeCiccio',
    office: 'Mayor of Winter Park',
    officeLevel: 'Mayor',
    party: 'Republican',
    jurisdiction: 'Orange County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Winter Park; former city commissioner.',
    socialMedia: {},
  },
  {
    id: 'oc-022',
    name: 'Bryan Nelson',
    office: 'Mayor of Apopka',
    officeLevel: 'Mayor',
    party: 'Republican',
    jurisdiction: 'Orange County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Apopka; long-serving mayor of the city.',
    socialMedia: {},
  },
  {
    id: 'oc-023',
    name: 'Rusty Johnson',
    office: 'Mayor of Ocoee',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Orange County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Ocoee; serves the western Orange County community.',
    socialMedia: {},
  },
  {
    id: 'oc-024',
    name: 'John Rees',
    office: 'Mayor of Winter Garden',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Orange County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Winter Garden; leads one of the fastest-growing cities in Orange County.',
    socialMedia: {},
  },
  {
    id: 'oc-025',
    name: 'John Lowndes',
    office: 'Mayor of Maitland',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Orange County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Maitland; serves the central Orange County suburb.',
    socialMedia: {},
  },
  {
    id: 'oc-026',
    name: 'Jason Carson',
    office: 'Mayor of Belle Isle',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Orange County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Belle Isle; leads the small enclave city south of Orlando.',
    socialMedia: {},
  },
  {
    id: 'oc-027',
    name: 'Angie Gardner',
    office: 'Mayor of Eatonville',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Orange County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Eatonville; leads one of the oldest incorporated African American municipalities in the U.S.',
    socialMedia: {},
  },
  {
    id: 'oc-028',
    name: 'Jim O\'Brien',
    office: 'Mayor of Windermere',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Orange County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Windermere; serves the affluent western Orange County community.',
    socialMedia: {},
  },
];
