import { Politician } from './types';

export const putnamCountyOfficials: Politician[] = [
  // ── COUNTY COMMISSIONERS ──────────────────────────────────────────────
  {
    id: 'pc-001',
    name: 'J.R. Newbold III',
    office: 'County Commissioner, District 1',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 1',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County Commissioner representing District 1.',
    socialMedia: {},
  },
  {
    id: 'pc-002',
    name: 'Leota Wilkinson',
    office: 'County Commissioner, District 2 (Chair)',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 2',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County Commissioner representing District 2, serving as Chair.',
    socialMedia: {},
  },
  {
    id: 'pc-003',
    name: 'Josh Alexander',
    office: 'County Commissioner, District 3',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 3',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County Commissioner representing District 3.',
    socialMedia: {},
  },
  {
    id: 'pc-004',
    name: 'Larry Harvey',
    office: 'County Commissioner, District 4',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 4',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County Commissioner representing District 4.',
    socialMedia: {},
  },
  {
    id: 'pc-005',
    name: 'Walton Pellicer',
    office: 'County Commissioner, District 5',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 5',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County Commissioner representing District 5.',
    socialMedia: {},
  },

  // ── CONSTITUTIONAL OFFICERS ───────────────────────────────────────────
  {
    id: 'pc-006',
    name: 'H.D. "Gator" DeLoach',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Sheriff of Putnam County.',
    socialMedia: {},
  },
  {
    id: 'pc-007',
    name: 'Matt Reynolds',
    office: 'Clerk of Circuit Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Clerk of Circuit Court for Putnam County.',
    socialMedia: {},
  },
  {
    id: 'pc-008',
    name: 'Clay A. Davis',
    office: 'Property Appraiser',
    officeLevel: 'Property Appraiser',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Property Appraiser for Putnam County.',
    socialMedia: {},
  },
  {
    id: 'pc-009',
    name: 'Brenda Bridges',
    office: 'Tax Collector',
    officeLevel: 'Tax Collector',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Tax Collector for Putnam County.',
    socialMedia: {},
  },
  {
    id: 'pc-010',
    name: 'Charles L. Overturf III',
    office: 'Supervisor of Elections',
    officeLevel: 'Supervisor of Elections',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 4,
    isActive: true,
    tags: [],
    bio: 'Supervisor of Elections for Putnam County.',
    socialMedia: {},
  },

  // ── SCHOOL BOARD ──────────────────────────────────────────────────────
  {
    id: 'pc-011',
    name: 'Holly Pickens',
    office: 'School Board Member, District 1',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 1',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County School Board member representing District 1.',
    socialMedia: {},
  },
  {
    id: 'pc-012',
    name: 'David M. Buckles',
    office: 'School Board Member, District 2',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 2',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County School Board member representing District 2.',
    socialMedia: {},
  },
  {
    id: 'pc-013',
    name: 'Sandra Gilyard',
    office: 'School Board Member, District 3 (Chair)',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 3',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County School Board member representing District 3, serving as Chair.',
    socialMedia: {},
  },
  {
    id: 'pc-014',
    name: 'Linda Wagner',
    office: 'School Board Member, District 4 (Vice Chair)',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 4',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County School Board member representing District 4, serving as Vice Chair.',
    socialMedia: {},
  },
  {
    id: 'pc-015',
    name: 'Phil Leary',
    office: 'School Board Member, District 5',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 5',
    jurisdiction: 'Putnam County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Putnam County School Board member representing District 5.',
    socialMedia: {},
  },

  // ── PALATKA ───────────────────────────────────────────────────────────
  {
    id: 'pc-016',
    name: 'Robbi Correa',
    office: 'Mayor of Palatka',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    district: 'Citywide',
    jurisdiction: 'Palatka',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Mayor of Palatka.',
    socialMedia: {},
  },
  {
    id: 'pc-017',
    name: 'Annie Henderson Davis',
    office: 'Commissioner, Group 1',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'Group 1',
    jurisdiction: 'Palatka',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Palatka City Commissioner representing Group 1.',
    socialMedia: {},
  },
  {
    id: 'pc-018',
    name: 'Justin Campbell',
    office: 'Commissioner, Group 2',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'Group 2',
    jurisdiction: 'Palatka',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Palatka City Commissioner representing Group 2.',
    socialMedia: {},
  },
  {
    id: 'pc-019',
    name: 'Will Jones',
    office: 'Commissioner, Group 3',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'Group 3',
    jurisdiction: 'Palatka',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Palatka City Commissioner representing Group 3.',
    socialMedia: {},
  },
  {
    id: 'pc-020',
    name: 'Rufus Borom',
    office: 'Commissioner, Group 4',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'Group 4',
    jurisdiction: 'Palatka',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Palatka City Commissioner representing Group 4.',
    socialMedia: {},
  },

  // ── CRESCENT CITY ─────────────────────────────────────────────────────
  {
    id: 'pc-021',
    name: 'Michele Myers',
    office: 'Mayor of Crescent City',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    district: 'Citywide',
    jurisdiction: 'Crescent City',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Mayor of Crescent City.',
    socialMedia: {},
  },
  {
    id: 'pc-022',
    name: 'William "B.J." Laurie',
    office: 'Vice Mayor/Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Crescent City',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Vice Mayor and Commissioner of Crescent City.',
    socialMedia: {},
  },
  {
    id: 'pc-023',
    name: 'Linda Moore',
    office: 'Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Crescent City',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Crescent City Commissioner.',
    socialMedia: {},
  },
  {
    id: 'pc-024',
    name: 'Lisa Kane DeVitto',
    office: 'Commissioner',
    officeLevel: 'City Commissioner',
    party: 'Nonpartisan',
    district: 'At-Large',
    jurisdiction: 'Crescent City',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Crescent City Commissioner.',
    socialMedia: {},
  },
];
