import { Politician } from './types';

export const seminoleCountyOfficials: Politician[] = [
  // ─── COUNTY COMMISSIONERS ───────────────────────────────────────────
  {
    id: 'sc-001',
    name: 'Bob Dallari',
    office: 'County Commissioner',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 1',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County Commissioner for District 1, long-serving official focused on transportation and infrastructure.',
    socialMedia: {},
  },
  {
    id: 'sc-002',
    name: 'Jay Zembower',
    office: 'County Commissioner',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 2',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County Commissioner for District 2, advocating for economic development and public safety.',
    socialMedia: {},
  },
  {
    id: 'sc-003',
    name: 'Lee Constantine',
    office: 'County Commissioner',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 3',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County Commissioner for District 3, environmental advocate and supporter of Wekiva River protection.',
    socialMedia: {},
  },
  {
    id: 'sc-004',
    name: 'Amy Lockhart',
    office: 'County Commissioner',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 4',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County Commissioner for District 4, focused on community development and fiscal responsibility.',
    socialMedia: {},
  },
  {
    id: 'sc-005',
    name: 'Andria Herr',
    office: 'County Commissioner, Chair',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 5',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Chair of the Seminole County Board of County Commissioners representing District 5.',
    socialMedia: {},
  },

  // ─── CONSTITUTIONAL OFFICERS ────────────────────────────────────────
  {
    id: 'sc-006',
    name: 'Dennis Lemma',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County Sheriff leading law enforcement and public safety operations across the county.',
    socialMedia: {},
  },
  {
    id: 'sc-007',
    name: 'Grant Maloy',
    office: 'Clerk of Circuit Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County Clerk of Circuit Court and Comptroller managing court records and county finances.',
    socialMedia: {},
  },
  {
    id: 'sc-008',
    name: 'David Johnson',
    office: 'Property Appraiser',
    officeLevel: 'Property Appraiser',
    party: 'Republican',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County Property Appraiser responsible for assessing the value of all property in the county.',
    socialMedia: {},
  },
  {
    id: 'sc-009',
    name: 'J.R. Kroll',
    office: 'Tax Collector',
    officeLevel: 'Tax Collector',
    party: 'Republican',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County Tax Collector overseeing tax collection, tag and title services, and hunting/fishing licenses.',
    socialMedia: {},
  },
  {
    id: 'sc-010',
    name: 'Amy Pennock',
    office: 'Supervisor of Elections',
    officeLevel: 'Supervisor of Elections',
    party: 'Republican',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County Supervisor of Elections managing voter registration and election integrity.',
    socialMedia: {},
  },

  // ─── SCHOOL BOARD ───────────────────────────────────────────────────
  {
    id: 'sc-011',
    name: 'Kristine Kraus',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 1',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County School Board member for District 1, supporting academic excellence and teacher development.',
    socialMedia: {},
  },
  {
    id: 'sc-012',
    name: 'Kelley Davis',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 2',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County School Board member for District 2, focused on school safety and student mental health resources.',
    socialMedia: {},
  },
  {
    id: 'sc-013',
    name: 'Abby Sanchez',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 3',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County School Board member for District 3, advocating for parental involvement and curriculum transparency.',
    socialMedia: {},
  },
  {
    id: 'sc-014',
    name: 'Robin Dehlinger',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 4',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County School Board member for District 4, dedicated to improving educational facilities and technology.',
    socialMedia: {},
  },
  {
    id: 'sc-015',
    name: 'Autumn Garick',
    office: 'School Board Member',
    officeLevel: 'School Board',
    party: 'Nonpartisan',
    district: 'District 5',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Seminole County School Board member for District 5, committed to inclusive education and workforce readiness.',
    socialMedia: {},
  },

  // ─── MAYORS ─────────────────────────────────────────────────────────
  {
    id: 'sc-016',
    name: 'Art Woodruff',
    office: 'Mayor of Sanford',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Sanford, the county seat of Seminole County, leading waterfront revitalization and economic growth.',
    socialMedia: {},
  },
  {
    id: 'sc-017',
    name: 'Patricia "Pat" Bates',
    office: 'Mayor of Altamonte Springs',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Altamonte Springs, overseeing one of Central Florida\'s most vibrant suburban cities.',
    socialMedia: {},
  },
  {
    id: 'sc-018',
    name: 'David Henson',
    office: 'Mayor of Casselberry',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Casselberry, focused on parks and recreation improvements and neighborhood revitalization.',
    socialMedia: {},
  },
  {
    id: 'sc-019',
    name: 'David Mealor',
    office: 'Mayor of Lake Mary',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Lake Mary, supporting the city\'s role as a corporate hub and family-friendly community.',
    socialMedia: {},
  },
  {
    id: 'sc-020',
    name: 'Brian Sackett',
    office: 'Mayor of Longwood',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Longwood, preserving the city\'s historic district while encouraging smart growth.',
    socialMedia: {},
  },
  {
    id: 'sc-021',
    name: 'Megan Sladek',
    office: 'Mayor of Oviedo',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Oviedo, leading a rapidly growing city known for its community events and natural areas.',
    socialMedia: {},
  },
  {
    id: 'sc-022',
    name: 'Kevin McCann',
    office: 'Mayor of Winter Springs',
    officeLevel: 'Mayor',
    party: 'Nonpartisan',
    jurisdiction: 'Seminole County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 2,
    isActive: true,
    tags: [],
    bio: 'Mayor of Winter Springs, focused on maintaining quality of life and expanding recreational amenities.',
    socialMedia: {},
  },
];
