import { Politician } from './types';

// Volusia County, Florida Officials (2026)
// County seat: DeLand
// Population: ~580,000

export const volusiaCountyOfficials: Politician[] = [
  // County Council (7 members)
  {
    id: 'vc-001',
    name: 'Jeff Brower',
    office: 'Volusia County Chair',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'At-Large',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 28,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Chair, elected countywide. Presides over County Council meetings and serves as ceremonial representative.',
    socialMedia: {},
  },
  {
    id: 'vc-002',
    name: 'Danny Robins',
    office: 'County Council At-Large',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'At-Large',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 32,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Volusia County Council Member representing all of Volusia County (At-Large seat).',
    socialMedia: {},
  },
  {
    id: 'vc-003',
    name: 'Matt Reinhart',
    office: 'County Council District 1',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 1',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 25,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Council Member representing District 1 (DeLand area).',
    socialMedia: {},
  },
  {
    id: 'vc-004',
    name: 'David Santiago',
    office: 'County Council District 2',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 2',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 30,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Volusia County Council Member representing District 2 (Deltona area).',
    socialMedia: {},
  },
  {
    id: 'vc-005',
    name: 'Billie Wheeler',
    office: 'County Council District 3',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 3',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 27,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Council Member representing District 3 (Daytona Beach area).',
    socialMedia: {},
  },
  {
    id: 'vc-006',
    name: 'Rob Long',
    office: 'County Council District 4',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 4',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 29,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Volusia County Council Member representing District 4 (Ormond Beach/Palm Coast area).',
    socialMedia: {},
  },
  {
    id: 'vc-007',
    name: 'Don Dempsey',
    office: 'County Council District 5',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 5',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 26,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Council Member representing District 5 (New Smyrna Beach/Edgewater area).',
    socialMedia: {},
  },

  // Constitutional Officers
  {
    id: 'vc-008',
    name: 'Mike Chitwood',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Democrat',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 35,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [],
    bio: 'Volusia County Sheriff. Oversees law enforcement operations across Volusia County.',
    socialMedia: {
      twitterHandle: 'SheriffChitwood',
      facebookPageUrl: 'https://www.facebook.com/VolusiaSheriff',
    },
  },
  {
    id: 'vc-009',
    name: 'Lisa Lewis',
    office: 'Supervisor of Elections',
    officeLevel: 'Supervisor of Elections',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 22,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Supervisor of Elections. Manages voter registration and elections administration.',
    socialMedia: {},
  },
  {
    id: 'vc-010',
    name: 'Larry Bartlett',
    office: 'Property Appraiser',
    officeLevel: 'Property Appraiser',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 24,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Property Appraiser. Determines property values for tax assessment purposes.',
    socialMedia: {},
  },
  {
    id: 'vc-011',
    name: 'Will Roberts',
    office: 'Tax Collector',
    officeLevel: 'Tax Collector',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 23,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Tax Collector. Collects property taxes, issues license plates, and processes driver licenses.',
    socialMedia: {},
  },
  {
    id: 'vc-012',
    name: 'Gary Davidson',
    office: 'Clerk of Circuit Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 21,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Clerk of Circuit Court. Maintains court records and serves as County Comptroller.',
    socialMedia: {},
  },
];
