import { Politician } from './types';

// Volusia County, Florida Officials (2026)
// County seat: DeLand
// Population: ~580,000

export const volusiaCountyOfficials: Politician[] = [
  // County Council (7 members)
  {
    id: 'vc-001',
    name: 'Jeff Brower',
    office: 'Volusia County Chair',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'At-Large',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 28,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Chair, elected countywide. Presides over County Council meetings and serves as ceremonial representative.',
    socialMedia: {},
  },
  {
    id: 'vc-002',
    name: 'Danny Robins',
    office: 'County Council At-Large',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'At-Large',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 32,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Volusia County Council Member representing all of Volusia County (At-Large seat).',
    socialMedia: {},
  },
  {
    id: 'vc-003',
    name: 'Matt Reinhart',
    office: 'County Council District 1',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 1',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 25,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Council Member representing District 1 (DeLand area).',
    socialMedia: {},
  },
  {
    id: 'vc-004',
    name: 'David Santiago',
    office: 'County Council District 2',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 2',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 30,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Volusia County Council Member representing District 2 (Deltona area).',
    socialMedia: {},
  },
  {
    id: 'vc-005',
    name: 'Billie Wheeler',
    office: 'County Council District 3',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 3',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 27,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Council Member representing District 3 (Daytona Beach area).',
    socialMedia: {},
  },
  {
    id: 'vc-006',
    name: 'Rob Long',
    office: 'County Council District 4',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 4',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 29,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [],
    bio: 'Volusia County Council Member representing District 4 (Ormond Beach/Palm Coast area).',
    socialMedia: {},
  },
  {
    id: 'vc-007',
    name: 'Don Dempsey',
    office: 'County Council District 5',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'District 5',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 26,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2023-01-01',
    termEnd: '2027-01-01',
    yearsInOffice: 3,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Council Member representing District 5 (New Smyrna Beach/Edgewater area).',
    socialMedia: {},
  },

  // Constitutional Officers
  {
    id: 'vc-008',
    name: 'Mike Chitwood',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Democrat',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 35,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [],
    bio: 'Volusia County Sheriff. Oversees law enforcement operations across Volusia County.',
    socialMedia: {
      twitterHandle: 'SheriffChitwood',
      facebookPageUrl: 'https://www.facebook.com/VolusiaSheriff',
    },
  },
  {
    id: 'vc-009',
    name: 'Lisa Lewis',
    office: 'Supervisor of Elections',
    officeLevel: 'Supervisor of Elections',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 22,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Supervisor of Elections. Manages voter registration and elections administration.',
    socialMedia: {},
  },
  {
    id: 'vc-010',
    name: 'Larry Bartlett',
    office: 'Property Appraiser',
    officeLevel: 'Property Appraiser',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 24,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Property Appraiser. Determines property values for tax assessment purposes.',
    socialMedia: {},
  },
  {
    id: 'vc-011',
    name: 'Will Roberts',
    office: 'Tax Collector',
    officeLevel: 'Tax Collector',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 23,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Tax Collector. Collects property taxes, issues license plates, and processes driver licenses.',
    socialMedia: {},
  },
  {
    id: 'vc-012',
    name: 'Gary Davidson',
    office: 'Clerk of Circuit Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    district: 'Countywide',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 21,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    termStart: '2017-01-01',
    yearsInOffice: 9,
    isActive: true,
    tags: [
      { type: 'clean', label: 'Clean Record', color: '#10B981' },
    ],
    bio: 'Volusia County Clerk of Circuit Court. Maintains court records and serves as County Comptroller.',
    socialMedia: {},
  },

  // =========================================================================
  // School Board (Nonpartisan)
  // =========================================================================
  {
    id: 'vc-013', name: 'Jamie Haynes', office: 'School Board District 1',
    officeLevel: 'School Board', party: 'Nonpartisan', district: 'District 1',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County School Board Member, District 1 (DeLand, DeBary, Orange City area).',
  },
  {
    id: 'vc-014', name: 'Krista Goodrich', office: 'School Board District 2',
    officeLevel: 'School Board', party: 'Nonpartisan', district: 'District 2',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County School Board Member, District 2. Vice Chair.',
  },
  {
    id: 'vc-015', name: 'Jessie Thompson', office: 'School Board District 3',
    officeLevel: 'School Board', party: 'Nonpartisan', district: 'District 3',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County School Board Member, District 3 (Edgewater, New Smyrna Beach, Port Orange area).',
  },
  {
    id: 'vc-016', name: 'Donna Brosemer', office: 'School Board District 4',
    officeLevel: 'School Board', party: 'Nonpartisan', district: 'District 4',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County School Board Member, District 4. Elected November 2024.',
  },
  {
    id: 'vc-017', name: 'Ruben Colon', office: 'School Board District 5',
    officeLevel: 'School Board', party: 'Nonpartisan', district: 'District 5',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County School Board Chair, District 5. First elected 2018.',
  },
  {
    id: 'vc-018', name: 'Dr. Carmen Balgobin', office: 'Superintendent of Schools',
    officeLevel: 'School Board', party: 'Nonpartisan', district: 'Countywide',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County Superintendent of Schools. 2025 National Superintendent of the Year (NASS). Contract through 2029.',
  },

  // =========================================================================
  // City Mayors (Nonpartisan offices)
  // =========================================================================
  {
    id: 'vc-019', name: 'Derrick L. Henry', office: 'Mayor, Daytona Beach',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Daytona Beach',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Daytona Beach. 4th term, serving since 2012.',
  },
  {
    id: 'vc-020', name: 'Nancy Miller', office: 'Mayor, Daytona Beach Shores',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Daytona Beach Shores',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Daytona Beach Shores. President of FL League of Mayors. Term through Nov 2026.',
  },
  {
    id: 'vc-021', name: 'Karen Chasez', office: 'Mayor, DeBary',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'DeBary',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of DeBary. Term Jan 2023 - Dec 2026.',
  },
  {
    id: 'vc-022', name: 'Chris Cloudman', office: 'Mayor, DeLand',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'DeLand',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of DeLand. New mayor as of 2025, first new DeLand mayor in 21 years.',
  },
  {
    id: 'vc-023', name: 'Santiago Avila Jr.', office: 'Mayor, Deltona',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Deltona',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Deltona. First Hispanic mayor elected in Deltona.',
  },
  {
    id: 'vc-024', name: 'Diezel Depew', office: 'Mayor, Edgewater',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Edgewater',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Edgewater.',
  },
  {
    id: 'vc-025', name: 'John Penny', office: 'Mayor, Holly Hill',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Holly Hill',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Holly Hill.',
  },
  {
    id: 'vc-026', name: 'Roger Eckert', office: 'Mayor, Lake Helen',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Lake Helen',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Lake Helen.',
  },
  {
    id: 'vc-027', name: 'Fred Cleveland', office: 'Mayor, New Smyrna Beach',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'New Smyrna Beach',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of New Smyrna Beach. First elected 2022, re-elected 2024.',
  },
  {
    id: 'vc-028', name: 'Kelli Marks', office: 'Mayor, Orange City',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Orange City',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Orange City.',
  },
  {
    id: 'vc-029', name: 'Jason Leslie', office: 'Mayor, Ormond Beach',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Ormond Beach',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Ormond Beach. Elected Nov 2024.',
  },
  {
    id: 'vc-030', name: 'D. Gray Leonhart', office: 'Mayor, Pierson',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Pierson',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Pierson.',
  },
  {
    id: 'vc-031', name: 'Lois Paritsky', office: 'Mayor, Ponce Inlet',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Ponce Inlet',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Ponce Inlet.',
  },
  {
    id: 'vc-032', name: 'Scott Stiltner', office: 'Mayor, Port Orange',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Port Orange',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Port Orange. Sworn in Dec 2024, term through Dec 2028.',
  },
  {
    id: 'vc-033', name: 'William C. Hall', office: 'Mayor, South Daytona',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'South Daytona',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of South Daytona.',
  },
  {
    id: 'vc-034', name: 'Ricky Taylor', office: 'Mayor, Oak Hill',
    officeLevel: 'Mayor', party: 'Nonpartisan', district: 'Oak Hill',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Mayor of Oak Hill.',
  },

  // =========================================================================
  // Daytona Beach City Commission (Nonpartisan)
  // =========================================================================
  {
    id: 'vc-035', name: 'Monica Paris', office: 'Daytona Beach City Commissioner Zone 1',
    officeLevel: 'City Commissioner', party: 'Nonpartisan', district: 'Zone 1',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Daytona Beach City Commissioner, Zone 1.',
  },
  {
    id: 'vc-036', name: 'Ken Strickland', office: 'Daytona Beach City Commissioner Zone 2',
    officeLevel: 'City Commissioner', party: 'Nonpartisan', district: 'Zone 2',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Daytona Beach City Commissioner, Zone 2.',
  },
  {
    id: 'vc-037', name: 'Quanita May', office: 'Daytona Beach City Commissioner Zone 3',
    officeLevel: 'City Commissioner', party: 'Nonpartisan', district: 'Zone 3',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Daytona Beach City Commissioner, Zone 3.',
  },
  {
    id: 'vc-038', name: 'Stacy Cantu', office: 'Daytona Beach City Commissioner Zone 4',
    officeLevel: 'City Commissioner', party: 'Nonpartisan', district: 'Zone 4',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Daytona Beach City Commissioner, Zone 4.',
  },
  {
    id: 'vc-039', name: 'Dannette Henry', office: 'Daytona Beach City Commissioner Zone 5',
    officeLevel: 'City Commissioner', party: 'Nonpartisan', district: 'Zone 5',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Daytona Beach City Commissioner, Zone 5.',
  },
  {
    id: 'vc-040', name: 'Paula R. Reed', office: 'Daytona Beach City Commissioner Zone 6',
    officeLevel: 'City Commissioner', party: 'Nonpartisan', district: 'Zone 6',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Daytona Beach City Commissioner, Zone 6.',
  },

  // =========================================================================
  // 7th Judicial Circuit — State Attorney & Public Defender
  // =========================================================================
  {
    id: 'vc-041', name: 'R.J. Larizza', office: 'State Attorney, 7th Judicial Circuit',
    officeLevel: 'State Attorney', party: 'Republican', district: '7th Judicial Circuit',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    termStart: '2009-01-01', isActive: true, tags: [], socialMedia: {},
    bio: 'State Attorney for the 7th Judicial Circuit (Volusia, Flagler, Putnam, St. Johns). In office since 2009.',
  },
  {
    id: 'vc-042', name: 'Matthew Metz', office: 'Public Defender, 7th Judicial Circuit',
    officeLevel: 'Public Defender', party: 'Republican', district: '7th Judicial Circuit',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    termStart: '2021-01-01', isActive: true, tags: [], socialMedia: {},
    bio: 'Public Defender for the 7th Judicial Circuit. Elected 2020.',
  },

  // =========================================================================
  // Soil & Water Conservation District (Nonpartisan)
  // =========================================================================
  {
    id: 'vc-043', name: 'Kristine Cunningham', office: 'Soil & Water Conservation Supervisor',
    officeLevel: 'Soil & Water', party: 'Nonpartisan', district: 'District 5',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County Soil & Water Conservation District Chair, District 5.',
  },
  {
    id: 'vc-044', name: 'Austin Spivey', office: 'Soil & Water Conservation Supervisor',
    officeLevel: 'Soil & Water', party: 'Nonpartisan', district: 'District 1',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County Soil & Water Conservation District Vice Chair, District 1.',
  },
  {
    id: 'vc-045', name: 'Wendy Anderson', office: 'Soil & Water Conservation Supervisor',
    officeLevel: 'Soil & Water', party: 'Nonpartisan', district: 'District 4',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County Soil & Water Conservation District Treasurer, District 4.',
  },
  {
    id: 'vc-046', name: 'Erin Miceli', office: 'Soil & Water Conservation Supervisor',
    officeLevel: 'Soil & Water', party: 'Nonpartisan', district: 'District 3',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County Soil & Water Conservation District Secretary, District 3.',
  },
  {
    id: 'vc-047', name: 'David Bagley', office: 'Soil & Water Conservation Supervisor',
    officeLevel: 'Soil & Water', party: 'Nonpartisan', district: 'District 2',
    jurisdiction: 'Volusia County', jurisdictionType: 'county',
    corruptionScore: 0, juiceBoxTier: 'none', aipacFunding: 0,
    isActive: true, tags: [], socialMedia: {},
    bio: 'Volusia County Soil & Water Conservation District Supervisor, District 2.',
  },

  // =========================================================================
  // Circuit Court Judges — 7th Judicial Circuit (Nonpartisan)
  // =========================================================================
  ...([
    ['vc-048', 'R. Lee Smith', 'Circuit Judge Group 1'],
    ['vc-049', 'Kenneth J. Janesk II', 'Circuit Judge Group 2'],
    ['vc-050', 'Lauren Blocker', 'Circuit Judge Group 3'],
    ['vc-051', 'Dennis Craig', 'Circuit Judge Group 5'],
    ['vc-052', 'Michael S. Orfinger', 'Circuit Judge Group 6'],
    ['vc-053', 'Robert W. Pickens III', 'Circuit Judge Group 7'],
    ['vc-054', 'Christopher A. France', 'Circuit Judge Group 8'],
    ['vc-055', 'Chris Miller', 'Circuit Judge Group 9'],
    ['vc-056', 'Christopher Ferebee', 'Circuit Judge Group 10'],
    ['vc-057', 'Rose Marie Karadsheh Preddy', 'Circuit Judge Group 11'],
    ['vc-058', 'Mary G. Jolley', 'Circuit Judge Group 12'],
    ['vc-059', 'Kathleen McNeilly', 'Circuit Judge Group 13'],
    ['vc-060', 'Joan Anthony', 'Circuit Judge Group 14'],
    ['vc-061', 'Linda L. Gaustad', 'Circuit Judge Group 15'],
    ['vc-062', 'Leah R. Case', 'Chief Judge, Circuit Group 16'],
    ['vc-063', 'Howard O. McGillin Jr.', 'Circuit Judge Group 17'],
    ['vc-064', 'Karen A. Foxman', 'Circuit Judge Group 18'],
    ['vc-065', 'Howard M. Maltz', 'Circuit Judge Group 19'],
    ['vc-066', 'Kathryn D. Weston', 'Circuit Judge Group 20'],
    ['vc-067', 'Elizabeth A. Blackburn', 'Circuit Judge Group 21'],
    ['vc-068', 'Dawn D. Nichols', 'Circuit Judge Group 22'],
    ['vc-069', 'Christopher Kelly', 'Circuit Judge Group 23'],
    ['vc-070', 'Sandra C. Upchurch', 'Circuit Judge Group 24'],
    ['vc-071', 'David S. Wainer III', 'Circuit Judge Group 25'],
    ['vc-072', 'Randell H. Rowe III', 'Circuit Judge Group 26'],
    ['vc-073', 'Alicia R. Washington', 'Circuit Judge Group 27'],
  ] as const).map(([id, name, office]) => ({
    id, name, office,
    officeLevel: 'Judge' as const,
    party: 'Nonpartisan' as const,
    district: '7th Judicial Circuit',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county' as const,
    corruptionScore: 0,
    juiceBoxTier: 'none' as const,
    aipacFunding: 0,
    isActive: true,
    tags: [] as { type: string; label: string; color: string }[],
    socialMedia: {},
    bio: `${office}, 7th Judicial Circuit (Volusia, Flagler, Putnam, St. Johns counties).`,
  })),

  // =========================================================================
  // County Court Judges — Volusia County (Nonpartisan)
  // =========================================================================
  ...([
    ['vc-074', 'Joseph LeDonne', 'County Judge Group 1'],
    ['vc-075', 'Katherine H. Miller', 'County Judge Group 2'],
    ['vc-076', 'David A. Cromartie', 'County Judge Group 3'],
    ['vc-077', 'Rachel D. Myers', 'County Judge Group 4'],
    ['vc-078', 'Wesley Heidt', 'County Judge Group 5'],
    ['vc-079', 'Michelle Simonsen', 'County Judge Group 6'],
    ['vc-080', 'David H. Foxman', 'County Judge Group 7'],
    ['vc-081', 'Bryan A. Feigenbaum', 'County Judge Group 8'],
    ['vc-082', 'Robert A. Sanders Jr.', 'County Judge Group 9'],
    ['vc-083', 'Angela A. Dempsey', 'County Judge Group 10'],
  ] as const).map(([id, name, office]) => ({
    id, name, office,
    officeLevel: 'Judge' as const,
    party: 'Nonpartisan' as const,
    district: 'Volusia County',
    jurisdiction: 'Volusia County',
    jurisdictionType: 'county' as const,
    corruptionScore: 0,
    juiceBoxTier: 'none' as const,
    aipacFunding: 0,
    isActive: true,
    tags: [] as { type: string; label: string; color: string }[],
    socialMedia: {},
    bio: `${office}, Volusia County Court.`,
  })),
];
