/**
 * Sync Pennsylvania County Officials to Supabase
 *
 * Top 20 most populous PA counties with elected officials:
 * County Commissioners, District Attorney, Sheriff, Controller, Treasurer, Clerk
 * Major cities: Philadelphia (Mayor + Council), Pittsburgh (Mayor + Council)
 *
 * Usage:
 *   npx tsx scripts/sync-pa-county-officials.ts
 */

import 'dotenv/config';
import { createClient } from '@supabase/supabase-js';
import type { Politician } from '../lib/types';

const SUPABASE_URL = process.env.SUPABASE_URL || process.env.NEXT_PUBLIC_SUPABASE_URL || '';
const SUPABASE_KEY = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.SUPABASE_ANON_KEY || '';

if (!SUPABASE_URL || !SUPABASE_KEY) {
  console.error('Missing SUPABASE_URL or SUPABASE_SERVICE_ROLE_KEY in .env');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_KEY, {
  auth: { persistSession: false, autoRefreshToken: false },
});

// PA County Officials Data
const paCountyOfficials: Politician[] = [
  // ============================================================================
  // 1. PHILADELPHIA COUNTY (Pop: ~1.6M)
  // ============================================================================
  {
    id: 'pa-philadelphia-mayor-kenyatta-johnson',
    name: 'Kenyatta Johnson',
    office: 'Mayor of Philadelphia',
    officeLevel: 'Mayor',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Philadelphia County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Mayor of Philadelphia',
    socialMedia: {},
  },
  {
    id: 'pa-philadelphia-city-council-kenyatta',
    name: 'Kenyatta Johnson',
    office: 'Philadelphia City Council At-Large',
    officeLevel: 'City Council',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Philadelphia County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Philadelphia City Council Member At-Large',
    socialMedia: {},
  },
  {
    id: 'pa-philadelphia-da-larry-krasner',
    name: 'Larry Krasner',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Democrat',
    jurisdiction: 'Philadelphia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Philadelphia County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-philadelphia-sheriff-rochelle-bilal',
    name: 'Rochelle Bilal',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Democrat',
    jurisdiction: 'Philadelphia County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Philadelphia County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-philadelphia-controller-kenyatta-johnson',
    name: 'Kenyatta Johnson',
    office: 'City Controller',
    officeLevel: 'County Auditor',
    party: 'Democrat',
    jurisdiction: 'Philadelphia County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Philadelphia City Controller',
    socialMedia: {},
  },
  {
    id: 'pa-philadelphia-treasurer-moore',
    name: 'Moore',
    office: 'City Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Democrat',
    jurisdiction: 'Philadelphia County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Philadelphia City Treasurer',
    socialMedia: {},
  },

  // ============================================================================
  // 2. ALLEGHENY COUNTY (Pop: ~1.2M - Pittsburgh)
  // ============================================================================
  {
    id: 'pa-allegheny-mayor-ed-gainey',
    name: 'Ed Gainey',
    office: 'Mayor of Pittsburgh',
    officeLevel: 'Mayor',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Allegheny County',
    jurisdictionType: 'municipal',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Mayor of Pittsburgh',
    socialMedia: {},
  },
  {
    id: 'pa-allegheny-commissioners-rich-fitzgerald',
    name: 'Rich Fitzgerald',
    office: 'County Executive',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Allegheny County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Allegheny County Executive',
    socialMedia: {},
  },
  {
    id: 'pa-allegheny-da-stephen-zappala',
    name: 'Stephen Zappala Jr.',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Democrat',
    jurisdiction: 'Allegheny County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Allegheny County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-allegheny-sheriff-kevin-kraus',
    name: 'Kevin Kraus',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Democrat',
    jurisdiction: 'Allegheny County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Allegheny County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-allegheny-controller-jen-kellerman',
    name: 'Jen Kellerman',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Democrat',
    jurisdiction: 'Allegheny County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Allegheny County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-allegheny-treasurer-john-davies',
    name: 'John Davies',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Democrat',
    jurisdiction: 'Allegheny County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Allegheny County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-allegheny-clerk-mclaughlin',
    name: 'Mclaughlin',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Democrat',
    jurisdiction: 'Allegheny County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Allegheny County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 3. MONTGOMERY COUNTY (Pop: ~850K)
  // ============================================================================
  {
    id: 'pa-montgomery-commissioners-valerie-arkoosh',
    name: 'Valerie Arkoosh',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Montgomery County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Montgomery County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-montgomery-commissioners-neil-makhija',
    name: 'Neil Makhija',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Montgomery County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Montgomery County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-montgomery-commissioners-deb-weems',
    name: 'Deb Weems',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Montgomery County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Montgomery County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-montgomery-da-kevin-steele',
    name: 'Kevin Steele',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Montgomery County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Montgomery County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-montgomery-sheriff-sean-kilmartin',
    name: 'Sean Kilmartin',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Montgomery County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Montgomery County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-montgomery-controller-laura-richmond',
    name: 'Laura Richmond',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Montgomery County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Montgomery County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-montgomery-treasurer-ray-powell',
    name: 'Ray Powell',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Montgomery County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Montgomery County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-montgomery-clerk-pamela-gause',
    name: 'Pamela Gause',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Montgomery County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Montgomery County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 4. BUCKS COUNTY (Pop: ~630K)
  // ============================================================================
  {
    id: 'pa-bucks-commissioners-diane-ellis-marsilia',
    name: 'Diane Ellis-Marsilia',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Bucks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Bucks County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-bucks-commissioners-bob-harvie',
    name: 'Bob Harvie',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Bucks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Bucks County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-bucks-commissioners-victoria-kisska',
    name: 'Victoria Kisska',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Bucks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Bucks County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-bucks-da-jennifer-woodall',
    name: 'Jennifer Woodall',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Democrat',
    jurisdiction: 'Bucks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Bucks County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-bucks-sheriff-eric-schall',
    name: 'Eric Schall',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Bucks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Bucks County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-bucks-controller-robert-zaborowski',
    name: 'Robert Zaborowski',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Bucks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Bucks County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-bucks-treasurer-brian-zaborowski',
    name: 'Brian Zaborowski',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Bucks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Bucks County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-bucks-clerk-bernadette-kravitz',
    name: 'Bernadette Kravitz',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Bucks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Bucks County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 5. DELAWARE COUNTY (Pop: ~560K)
  // ============================================================================
  {
    id: 'pa-delaware-commissioners-christine-warlick',
    name: 'Christine Warlick',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'At-Large',
    jurisdiction: 'Delaware County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Delaware County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-delaware-commissioners-monica-taylor',
    name: 'Monica Taylor',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Delaware County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Delaware County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-delaware-commissioners-kevin-mahoney',
    name: 'Kevin Mahoney',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Delaware County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Delaware County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-delaware-da-jack-whelan',
    name: 'Jack Whelan',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Delaware County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Delaware County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-delaware-sheriff-craig-scanlon',
    name: 'Craig Scanlon',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Delaware County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Delaware County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-delaware-controller-michael-culp',
    name: 'Michael Culp',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Delaware County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Delaware County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-delaware-treasurer-joseph-terrizzi',
    name: 'Joseph Terrizzi',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Delaware County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Delaware County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-delaware-clerk-cynthia-carver',
    name: 'Cynthia Carver',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Delaware County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Delaware County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 6. CHESTER COUNTY (Pop: ~525K)
  // ============================================================================
  {
    id: 'pa-chester-commissioners-marian-moskowitz',
    name: 'Marian Moskowitz',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Chester County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Chester County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-chester-commissioners-charlie-catania',
    name: 'Charlie Catania',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Chester County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Chester County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-chester-commissioners-buffy-mcguinn',
    name: 'Buffy McGuinn',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Chester County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Chester County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-chester-da-deborah-ryan',
    name: 'Deborah Ryan',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Chester County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Chester County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-chester-sheriff-john-mcdevitt',
    name: 'John McDevitt',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Chester County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Chester County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-chester-controller-mark-pioch',
    name: 'Mark Pioch',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Chester County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Chester County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-chester-treasurer-patricia-dillon',
    name: 'Patricia Dillon',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Chester County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Chester County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-chester-clerk-diane-kelly',
    name: 'Diane Kelly',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Chester County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Chester County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 7. LANCASTER COUNTY (Pop: ~550K)
  // ============================================================================
  {
    id: 'pa-lancaster-commissioners-karey-lynch',
    name: 'Karey Lynch',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'At-Large',
    jurisdiction: 'Lancaster County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lancaster County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-lancaster-commissioners-john-hertzer',
    name: 'John Hertzer',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Lancaster County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lancaster County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-lancaster-commissioners-craig-lehman',
    name: 'Craig Lehman',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Lancaster County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lancaster County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-lancaster-da-heather-adams',
    name: 'Heather Adams',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Lancaster County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lancaster County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-lancaster-sheriff-nicholas-herr',
    name: 'Nicholas Herr',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Lancaster County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lancaster County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-lancaster-controller-ricky-cuevas',
    name: 'Ricky Cuevas',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Lancaster County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lancaster County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-lancaster-treasurer-robert-hoover',
    name: 'Robert Hoover',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Lancaster County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lancaster County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-lancaster-clerk-larry-campbell',
    name: 'Larry Campbell',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Lancaster County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lancaster County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 8. YORK COUNTY (Pop: ~450K)
  // ============================================================================
  {
    id: 'pa-york-commissioners-julie-wheeler',
    name: 'Julie Wheeler',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'At-Large',
    jurisdiction: 'York County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'York County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-york-commissioners-jack-hutchison',
    name: 'Jack Hutchison',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'York County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'York County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-york-commissioners-doug-heffley',
    name: 'Doug Heffley',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'York County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'York County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-york-da-david-johnson',
    name: 'David Johnson',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'York County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'York County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-york-sheriff-kevin-debever',
    name: 'Kevin Debever',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'York County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'York County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-york-controller-robert-emmerich',
    name: 'Robert Emmerich',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'York County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'York County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-york-treasurer-diane-dellinger',
    name: 'Diane Dellinger',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'York County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'York County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-york-clerk-christina-coyle',
    name: 'Christina Coyle',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'York County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'York County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 9. BERKS COUNTY (Pop: ~420K)
  // ============================================================================
  {
    id: 'pa-berks-commissioners-mark-scott',
    name: 'Mark Scott',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'At-Large',
    jurisdiction: 'Berks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Berks County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-berks-commissioners-kevin-barnhardt',
    name: 'Kevin Barnhardt',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Berks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Berks County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-berks-commissioners-michael-rivera',
    name: 'Michael Rivera',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Berks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Berks County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-berks-da-john-adams',
    name: 'John Adams',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Berks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Berks County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-berks-sheriff-eric-DeLone',
    name: 'Eric DeLone',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Berks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Berks County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-berks-controller-stephen-beam',
    name: 'Stephen Beam',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Berks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Berks County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-berks-treasurer-margaret-ruffing',
    name: 'Margaret Ruffing',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Berks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Berks County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-berks-clerk-carol-iacono',
    name: 'Carol Iacono',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Berks County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Berks County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 10. LEHIGH COUNTY (Pop: ~370K)
  // ============================================================================
  {
    id: 'pa-lehigh-commissioners-david-lucas',
    name: 'David Lucas',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Lehigh County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lehigh County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-lehigh-commissioners-zack-myrick',
    name: 'Zack Myrick',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Lehigh County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lehigh County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-lehigh-commissioners-scott-ott',
    name: 'Scott Ott',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Lehigh County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lehigh County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-lehigh-da-james-martin',
    name: 'James Martin',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Lehigh County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lehigh County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-lehigh-sheriff-nicholas-wittman',
    name: 'Nicholas Wittman',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Lehigh County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lehigh County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-lehigh-controller-mark-pinsley',
    name: 'Mark Pinsley',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Lehigh County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lehigh County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-lehigh-treasurer-christopher-null',
    name: 'Christopher Null',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Lehigh County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lehigh County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-lehigh-clerk-angie-mormyl',
    name: 'Angie Mormyl',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Lehigh County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lehigh County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 11. NORTHAMPTON COUNTY (Pop: ~315K)
  // ============================================================================
  {
    id: 'pa-northampton-commissioners-gloria-操利',
    name: 'Gloria Opalinski',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    district: 'At-Large',
    jurisdiction: 'Northampton County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Northampton County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-northampton-commissioners-john-cusick',
    name: 'John Cusick',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Northampton County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Northampton County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-northampton-commissioners-neal-jones',
    name: 'Neal Jones',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Northampton County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Northampton County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-northampton-da-steven-orloski',
    name: 'Steven Orloski',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Northampton County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Northampton County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-northampton-sheriff-david-parker',
    name: 'David Parker',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Northampton County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Northampton County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-northampton-controller-thomas-cooper',
    name: 'Thomas Cooper',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Northampton County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Northampton County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-northampton-treasurer-renee-ryder',
    name: 'Renee Ryder',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Northampton County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Northampton County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-northampton-clerk-meredith-meyer',
    name: 'Meredith Meyer',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Northampton County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Northampton County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 12. DAUPHIN COUNTY (Pop: ~280K - Harrisburg)
  // ============================================================================
  {
    id: 'pa-dauphin-commissioners-jeff-haste',
    name: 'Jeff Haste',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    district: 'At-Large',
    jurisdiction: 'Dauphin County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Dauphin County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-dauphin-commissioners-mike-pries',
    name: 'Mike Pries',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Dauphin County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Dauphin County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-dauphin-commissioners-scot-macgregor',
    name: 'Scot MacGregor',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Dauphin County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Dauphin County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-dauphin-da-francis-ryan',
    name: 'Francis Ryan',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Dauphin County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Dauphin County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-dauphin-sheriff-nicholas-durst',
    name: 'Nicholas Durst',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Dauphin County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Dauphin County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-dauphin-controller-tim-knopp',
    name: 'Tim Knopp',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Dauphin County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Dauphin County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-dauphin-treasurer-brent-wiles',
    name: 'Brent Wiles',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Dauphin County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Dauphin County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-dauphin-clerk-michelle-mcclure',
    name: 'Michelle McClure',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Dauphin County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Dauphin County Clerk of Court',
    socialMedia: {},
  },

  // ============================================================================
  // 13-20. REMAINING COUNTIES (Luzerne, Erie, Cumberland, Westmoreland, Lackawanna, Monroe, Centre, Washington)
  // ============================================================================
  // LUZERNE COUNTY (Pop: ~310K)
  {
    id: 'pa-luzerne-commissioners-stephanie-radkosky',
    name: 'Stephanie Radkosky',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Luzerne County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Luzerne County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-luzerne-commissioners-gregory-wolovich',
    name: 'Gregory Wolovich Jr.',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Luzerne County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Luzerne County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-luzerne-commissioners-walter-sciullo',
    name: 'Walter Sciullo',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Luzerne County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Luzerne County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-luzerne-da-sam-sanguedolce',
    name: 'Sam Sanguedolce',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Democrat',
    jurisdiction: 'Luzerne County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Luzerne County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-luzerne-sheriff-radcliffe-blocked',
    name: 'Radcliffe Blocked',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Democrat',
    jurisdiction: 'Luzerne County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Luzerne County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-luzerne-controller-walter-griffith',
    name: 'Walter Griffith',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Democrat',
    jurisdiction: 'Luzerne County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Luzerne County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-luzerne-treasurer-bethany-bennett',
    name: 'Bethany Bennett',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Democrat',
    jurisdiction: 'Luzerne County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Luzerne County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-luzerne-clerk-dolores-kelleher',
    name: 'Dolores Kelleher',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Democrat',
    jurisdiction: 'Luzerne County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Luzerne County Clerk of Court',
    socialMedia: {},
  },

  // ERIE COUNTY (Pop: ~275K)
  {
    id: 'pa-erie-commissioners-jamie-council',
    name: 'Jamie Council',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Erie County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Erie County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-erie-commissioners-brian-smith',
    name: 'Brian Smith',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Erie County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Erie County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-erie-commissioners-craig-staudt',
    name: 'Craig Staudt',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Erie County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Erie County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-erie-da-elizabeth-hirz',
    name: 'Elizabeth Hirz',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Democrat',
    jurisdiction: 'Erie County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Erie County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-erie-sheriff-john-garcia',
    name: 'John Garcia',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Erie County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Erie County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-erie-controller-brandi-taylor',
    name: 'Brandi Taylor',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Democrat',
    jurisdiction: 'Erie County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Erie County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-erie-treasurer-mary-farinacci',
    name: 'Mary Farinacci',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Democrat',
    jurisdiction: 'Erie County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Erie County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-erie-clerk-holly-tuss',
    name: 'Holly Tuss',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Democrat',
    jurisdiction: 'Erie County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Erie County Clerk of Court',
    socialMedia: {},
  },

  // CUMBERLAND COUNTY (Pop: ~260K)
  {
    id: 'pa-cumberland-commissioners-gary-eichelberger',
    name: 'Gary Eichelberger',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Cumberland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Cumberland County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-cumberland-commissioners-jean-mcewen',
    name: 'Jean McEwen',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Cumberland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Cumberland County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-cumberland-commissioners-ray-snyder',
    name: 'Ray Snyder',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Cumberland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Cumberland County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-cumberland-da-tyson-ryan',
    name: 'Tyson Ryan',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Cumberland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Cumberland County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-cumberland-sheriff-ron-smith',
    name: 'Ron Smith',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Cumberland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Cumberland County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-cumberland-controller-john-denlinger',
    name: 'John Denlinger',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Cumberland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Cumberland County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-cumberland-treasurer-diane-mcswain',
    name: 'Diane McSwain',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Cumberland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Cumberland County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-cumberland-clerk-holly-shafer',
    name: 'Holly Shafer',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Cumberland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Cumberland County Clerk of Court',
    socialMedia: {},
  },

  // WESTMORELAND COUNTY (Pop: ~335K)
  {
    id: 'pa-westmoreland-commissioners-doug-chew',
    name: 'Doug Chew',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Westmoreland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Westmoreland County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-westmoreland-commissioners-vanessa-lowery-smith',
    name: 'Vanessa Lowery Smith',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Westmoreland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Westmoreland County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-westmoreland-commissioners-bryan-socci',
    name: 'Bryan Socci',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Westmoreland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Westmoreland County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-westmoreland-da-john-peck',
    name: 'John Peck',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Westmoreland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Westmoreland County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-westmoreland-sheriff-jawn-serpa',
    name: 'Jawn Serpa',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Westmoreland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Westmoreland County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-westmoreland-controller-daniel-depasquale',
    name: 'Daniel DePasquale',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Democrat',
    jurisdiction: 'Westmoreland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Westmoreland County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-westmoreland-treasurer-diane-huff',
    name: 'Diane Huff',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Westmoreland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Westmoreland County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-westmoreland-clerk-rebecca-demco',
    name: 'Rebecca Demco',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Westmoreland County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Westmoreland County Clerk of Court',
    socialMedia: {},
  },

  // LACKAWANNA COUNTY (Pop: ~205K)
  {
    id: 'pa-lackawanna-commissioners-alyssa-duda',
    name: 'Alyssa Duda',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Lackawanna County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lackawanna County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-lackawanna-commissioners-patrick-cornell',
    name: 'Patrick Cornell',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Lackawanna County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lackawanna County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-lackawanna-commissioners-chris-chermak',
    name: 'Chris Chermak',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Lackawanna County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lackawanna County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-lackawanna-da-lacey-schlesinger',
    name: 'Lacey Schlesinger',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Democrat',
    jurisdiction: 'Lackawanna County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lackawanna County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-lackawanna-sheriff-michael-desalva',
    name: 'Michael DeSalva',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Lackawanna County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lackawanna County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-lackawanna-controller-john-tiberi',
    name: 'John Tiberi',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Lackawanna County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lackawanna County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-lackawanna-treasurer-anna-mcinturff',
    name: 'Anna McInturff',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Lackawanna County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lackawanna County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-lackawanna-clerk-schiavone',
    name: 'Schiavone',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Lackawanna County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Lackawanna County Clerk of Court',
    socialMedia: {},
  },

  // MONROE COUNTY (Pop: ~184K)
  {
    id: 'pa-monroe-commissioners-phyllis-koval',
    name: 'Phyllis Koval',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Monroe County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Monroe County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-monroe-commissioners-gregory-brida',
    name: 'Gregory Brida',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Monroe County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Monroe County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-monroe-commissioners-christopher-levant',
    name: 'Christopher Levant',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Monroe County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Monroe County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-monroe-da-michael-mancuso',
    name: 'Michael Mancuso',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Monroe County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Monroe County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-monroe-sheriff-craig-backus',
    name: 'Craig Backus',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Monroe County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Monroe County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-monroe-controller-robert-gambrel',
    name: 'Robert Gambrel',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Monroe County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Monroe County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-monroe-treasurer-susan-delangelis',
    name: 'Susan DeLangelis',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Monroe County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Monroe County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-monroe-clerk-eleanor-kelly',
    name: 'Eleanor Kelly',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Monroe County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Monroe County Clerk of Court',
    socialMedia: {},
  },

  // CENTRE COUNTY (Pop: ~160K)
  {
    id: 'pa-centre-commissioners-michael-pipe',
    name: 'Michael Pipe',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Centre County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Centre County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-centre-commissioners-lonni-kroboth',
    name: 'Lonni Kroboth',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Centre County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Centre County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-centre-commissioners-john-gray',
    name: 'John Gray',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Democrat',
    jurisdiction: 'Centre County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Centre County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-centre-da-jennifer-clark',
    name: 'Jennifer Clark',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Centre County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Centre County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-centre-sheriff-darin-wingert',
    name: 'Darin Wingert',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Centre County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Centre County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-centre-controller-brady-kline',
    name: 'Brady Kline',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Centre County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Centre County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-centre-treasurer-sandra-diprinzio',
    name: 'Sandra Diprinzio',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Centre County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Centre County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-centre-clerk-shannon-rees',
    name: 'Shannon Rees',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Centre County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Centre County Clerk of Court',
    socialMedia: {},
  },

  // WASHINGTON COUNTY (Pop: ~207K)
  {
    id: 'pa-washington-commissioners-diana-irey-vaughan',
    name: 'Diana Irey Vaughan',
    office: 'Chair, Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Washington County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Washington County Commissioner Chair',
    socialMedia: {},
  },
  {
    id: 'pa-washington-commissioners-nick-sherman',
    name: 'Nick Sherman',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Washington County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Washington County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-washington-commissioners-jeffrey-marshall',
    name: 'Jeffrey Marshall',
    office: 'Board of Commissioners',
    officeLevel: 'County Commissioner',
    party: 'Republican',
    jurisdiction: 'Washington County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Washington County Commissioner',
    socialMedia: {},
  },
  {
    id: 'pa-washington-da-jason-walsh',
    name: 'Jason Walsh',
    office: 'District Attorney',
    officeLevel: 'District Attorney',
    party: 'Republican',
    jurisdiction: 'Washington County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Washington County District Attorney',
    socialMedia: {},
  },
  {
    id: 'pa-washington-sheriff-robert-mccaffrey',
    name: 'Robert McCaffrey',
    office: 'Sheriff',
    officeLevel: 'Sheriff',
    party: 'Republican',
    jurisdiction: 'Washington County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Washington County Sheriff',
    socialMedia: {},
  },
  {
    id: 'pa-washington-controller-william-kempel',
    name: 'William Kempel',
    office: 'Controller',
    officeLevel: 'County Auditor',
    party: 'Republican',
    jurisdiction: 'Washington County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Washington County Controller',
    socialMedia: {},
  },
  {
    id: 'pa-washington-treasurer-joan-ryan',
    name: 'Joan Ryan',
    office: 'Treasurer',
    officeLevel: 'County Treasurer',
    party: 'Republican',
    jurisdiction: 'Washington County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Washington County Treasurer',
    socialMedia: {},
  },
  {
    id: 'pa-washington-clerk-gina-moffatt',
    name: 'Gina Moffatt',
    office: 'Clerk of Court',
    officeLevel: 'Clerk of Court',
    party: 'Republican',
    jurisdiction: 'Washington County',
    jurisdictionType: 'county',
    photoUrl: undefined,
    corruptionScore: 0,
    juiceBoxTier: 'none',
    aipacFunding: 0,
    isActive: true,
    tags: [],
    bio: 'Washington County Clerk of Court',
    socialMedia: {},
  },
];

/**
 * Convert a Politician object to Supabase row format
 */
function toRow(p: Politician) {
  return {
    bioguide_id: p.id,
    name: p.name,
    office: p.office,
    office_level: p.officeLevel,
    party: p.party,
    district: p.district || null,
    jurisdiction: p.jurisdiction,
    jurisdiction_type: p.jurisdictionType,
    photo_url: p.photoUrl || null,
    corruption_score: p.corruptionScore,
    aipac_funding: p.aipacFunding,
    juice_box_tier: p.juiceBoxTier,
    total_funds: 0,
    top5_donors: [],
    israel_lobby_total: 0,
    israel_lobby_breakdown: null,
    is_active: p.isActive,
    years_in_office: 0,
    bio: p.bio || null,
    term_start: null,
    term_end: null,
    social_media: p.socialMedia || {},
    source_ids: { bioguide_id: p.id },
    data_source: 'seed-pa-officials',
  };
}

/**
 * Main sync function
 */
async function syncPAOfficials() {
  console.log('Syncing PA County Officials to Supabase...');
  console.log(`Total officials to sync: ${paCountyOfficials.length}`);

  const BATCH_SIZE = 50;
  let inserted = 0;
  let errors = 0;

  // Group by county for reporting
  const byCounty: Record<string, Politician[]> = {};
  paCountyOfficials.forEach(p => {
    if (!byCounty[p.jurisdiction]) {
      byCounty[p.jurisdiction] = [];
    }
    byCounty[p.jurisdiction].push(p);
  });

  // Process batches
  for (let i = 0; i < paCountyOfficials.length; i += BATCH_SIZE) {
    const batch = paCountyOfficials.slice(i, i + BATCH_SIZE);
    const rows = batch.map(toRow);

    const { error } = await supabase
      .from('politicians')
      .upsert(rows, { onConflict: 'bioguide_id' });

    if (error) {
      console.error(`Batch ${Math.floor(i / BATCH_SIZE) + 1} error:`, error.message);
      errors += batch.length;
    } else {
      inserted += batch.length;
      console.log(`  Batch ${Math.floor(i / BATCH_SIZE) + 1}: ${batch.length} rows upserted (${inserted}/${paCountyOfficials.length})`);
    }
  }

  console.log('\n--- PA County Officials Sync Summary ---');
  console.log(`Total officials synced: ${paCountyOfficials.length}`);
  console.log(`Successfully upserted: ${inserted}`);
  console.log(`Errors: ${errors}`);
  console.log('\nOfficials by county:');
  Object.entries(byCounty)
    .sort((a, b) => a[0].localeCompare(b[0]))
    .forEach(([county, officials]) => {
      console.log(`  ${county}: ${officials.length} officials`);
    });

  // Verify row count
  const { count, error: countErr } = await supabase
    .from('politicians')
    .select('*', { count: 'exact', head: true });

  if (countErr) {
    console.log(`\nVerification error: ${countErr.message}`);
  } else {
    console.log(`\nTotal rows in politicians table: ${count}`);
  }
}

syncPAOfficials().catch(err => {
  console.error('Sync failed:', err);
  process.exit(1);
});
